#### numpy.array基本操作

In [9]:
import numpy as np
x = np.arange(15).reshape(3, 5)
# 数组维度
x.ndim
# 数组维度元组
x.shape
# 数组个数
x.size

15

#### numpy.array 数据访问

In [14]:
x[1, 3]

# 切片
x[:2, :3]

x[:2][:1]

# copy 复制原矩阵，并且新开内存

array([[0, 1, 2, 3, 4]])

#### Reshape

In [16]:
x.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
X = np.arange(10)
X.reshape(10 , -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [20]:
# 合并操作
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [21]:
a = np.array([[1,2,3],[4,5,6]])
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [27]:
b = np.arange(10)
np.vstack([x, a])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [30]:
x = np.arange(10)
x1, x2, x3 = np.split(x, [3, 7])
x1

array([0, 1, 2])

In [38]:
x = np.arange(15).reshape(3, 5)
a , b = np.vsplit(x, [2])
a
b
c = np.hsplit(x, [-1])
c

[array([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]]),
 array([[ 4],
        [ 9],
        [14]])]

In [44]:
L = [i for i in range(10)]
s = [2*e for e in L]
A = np.array(2*e for e in L)
A

array(<generator object <genexpr> at 0x05057CF0>, dtype=object)

In [47]:
L = np.arange(10)
A = 2*L
A + 1
A/3

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

#### 矩阵运算

In [54]:
a = np.arange(4).reshape(2,2)
b= np.full((2,2), 10)
a + b
a*b
a-b

array([[-10,  -9],
       [ -8,  -7]])

In [58]:
v = np.array([1,2])
a = np.array([[0,1],[2,3]])
v*a
v.dot(a)
a.dot(v)

array([2, 8])

In [63]:
a = np.arange(16).reshape(4, -1)
a.sum(axis=0)
a[0].mean()

1.5

In [67]:
x = np.random.normal(0, 1, size = 1000)
np.mean(x)

0.06761570321968925

In [80]:
np.argmax(x)

622

In [84]:
x[622]

3.359802224282565

In [78]:
np.max(x)

3.359802224282565

In [100]:
a = np.arange(16)
np.random.shuffle(a)
a.sort()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [101]:
a[3:9:2]
a[[3, 5, 8]]

array([3, 5, 8])

In [107]:
X = a.reshape(4, -1)
x = X[
    np.array([1, 2, 3]),
    np.array([0, 1, 2])
]
x

array([ 4,  9, 14])

In [108]:
X[1:3, [True, False, True, False]]

array([[ 4,  6],
       [ 8, 10]])

In [115]:
x = np.arange(16)
x < 3
x * 2 == 24 - 2*x

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False])

In [122]:
np.sum(x<3)
np.any(x < 0)
np.all(x > 0)
np.sum((x>3) & (x<7))

3