In [3]:
for i in range(5):
    print(i)

0
1
2
3
4


In [4]:
data = [i * 2 for i in range (50)]

In [5]:
len(data)

50

In [6]:
data[:10]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

#### %run 引用或者执行某个脚本

#### %timeit 脚本运行时间

In [7]:
%timeit L = [i**2 for i in range(19999)]

4.8 ms ± 69.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
%%timeit
L = []
for i in range (199):
    L.append(i**2)

51.6 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
#### time 运行内存

In [10]:
%time L = [i**2 for i in range(19999)]

Wall time: 5 ms


In [2]:
import numpy as np
numpy.__version__

'1.21.0'

In [4]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
nparr.dtype

dtype('int32')

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones(shape=(3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full(shape=(3,5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [15]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [16]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [24]:
np.random.randint(0, 10, size=10)

array([3, 1, 0, 2, 5, 0, 9, 1, 3, 0])

In [26]:
np.random.randint(0, 10, size = (3, 5))

array([[9, 2, 8, 2, 4],
       [1, 5, 9, 1, 3],
       [9, 6, 6, 7, 6]])

In [28]:
# np.random.seed(1111) 随机数的种子，可以保存
np.random.random([3, 5])

array([[0.50571794, 0.70907903, 0.81183437, 0.07646389, 0.77010886],
       [0.86067255, 0.08659693, 0.75812962, 0.7928439 , 0.88963857],
       [0.93429705, 0.52665312, 0.04436427, 0.16644297, 0.86645054]])

In [29]:
# random.normal() 符合正态分布的随机数
np.random.normal(0, 2, [3, 5
])

array([[ 1.76173738,  1.51555703, -0.7700291 ,  2.28177317,  0.8579404 ],
       [ 0.08159716, -0.33621579,  1.98402406,  1.20364216, -1.26400515],
       [-0.56107324,  2.89995683,  0.18017694,  3.72693425, -0.10982502]])